Updated check-nre-releases and release-package workflows

diff --git a/.github/workflows/release-package.yaml b/.github/workflows/release-package.yaml
--- a/.github/workflows/release-package.yaml
+++ b/.github/workflows/release-package.yaml
@@ -3,31 +3,96 @@ on:
   workflow_dispatch:
     inputs:
       package_name:
-        description: 'Name of the package to release'
+        description: "Name of the package to release"
         type: string
-        required: true
+        required: false
       revision:
-        description: 'SVN revision associated with the package version to release'
-        type: string
-        required: true
+        description: "SVN revision associated with the package version to release"
+        type: number
+        required: false
       version:
-        description: 'Version of the package to release'
+        description: "Version of the package to release"
         type: string
-        required: true
-run-name: "Release ${{ inputs.package_name }} ${{ inputs.version }}"
+        required: false
+      release_json:
+        description: "JSON object containing information on the packages to be released (ordered by 'package_name')"
+        type: string
+        required: false
 env:
-    TAG_NAME: ${{ inputs.package_name }}-${{ inputs.version }}
-    RELEASE_NAME: ${{ inputs.package_name }} ${{ inputs.version }}
+  RELEASE_WORKFLOW: release-package.yaml
 
 jobs:
+  inputs-sanity-check:
+    # This workflow accepts either a single 'release_json' input, or the three 
+    # 'package_name', 'revision' and 'version' inputs (without 'release_json').
+    # Make sure that the inputs are valid before proceeding.
+    name: Inputs sanity check
+    runs-on: ubuntu-latest
+    outputs:
+      package_name: ${{ steps.check-inputs.outputs.package_name }}
+      revision: ${{ steps.check-inputs.outputs.revision }}
+      version: ${{ steps.check-inputs.outputs.version }}
+      release_json: ${{ steps.check-inputs.outputs.release_json }}
+    steps:
+      - name: Check inputs
+        id: check-inputs
+        run: |
+          if [ -z '${{ inputs.release_json }}' ]; then
+            if (
+                [ -n '${{ inputs.package_name }}' ] \
+                || [ -n '${{ inputs.revision }}' ] \
+                || [ -n '${{ inputs.version }}' ] \
+            ); then
+              echo "::error:: 'release_json' cannot be specified together with any among 'package_name', 'revision' or 'version'." \
+                "Either a single 'release_json' input or the three 'package_name', 'revision' and 'version' inputs together must be specified."
+              exit 1
+            fi
+            echo "package_name='${{ inputs.package_name }}'" >> $GITHUB_OUTPUT
+            echo "revision='${{ inputs.revision }}'" >> $GITHUB_OUTPUT
+            echo "version='${{ inputs.version }}'" >> $GITHUB_OUTPUT
+            echo "release_json='${{ inputs.release_json }}'" >> $GITHUB_OUTPUT
+          elif (
+                [ -z '${{ inputs.package_name }}' ] \
+                || [ -z '${{ inputs.revision }}' ] \
+                || [ -z '${{ inputs.version }}' ] \
+          ); then
+            echo "::error:: Not enough input arguments specified. Either a single 'release_json' input or the three 'package_name', 'revision' and 'version' inputs together must be specified."
+            exit 1
+          else
+            # Take the release information from the first object in release_json array
+            echo "package_name=$(jq '.[0].package_name' <<< '${{ inputs.release_json }}')" >> $GITHUB_OUTPUT
+            echo "revision=$(jq '.[0].revision' <<< '${{ inputs.release_json }}')" >> $GITHUB_OUTPUT
+            echo "version=$(jq '.[0].version' <<< '${{ inputs.release_json }}')" >> $GITHUB_OUTPUT
+            # Remove the first object from the release_json array
+            echo "release_json=$(jq -c '.[1:]' <<< '${{ inputs.release_json }}')" >> $GITHUB_OUTPUT
+          fi
+
+  set-tag-name:
+    name: Set tag name and release name
+    runs-on: ubuntu-latest
+    needs: inputs-sanity-check
+    outputs:
+      tag_name: ${{ steps.set-tag.outputs.tag_name }}
+      release_name: ${{ steps.set-release.outputs.release_name }}
+    steps:
+      - name: Set tag name
+        id: set-tag
+        run: |
+          echo "tag_name=${{ needs.inputs-sanity-check.outputs.package_name }}-${{ needs.inputs-sanity-check.outputs.version }}" >> $GITHUB_OUTPUT
+      - name: Set release name
+        id: set-release
+        run: |
+          echo "release_name=${{ needs.inputs-sanity-check.outputs.package_name }} ${{ needs.inputs-sanity-check.outputs.version }}" >> $GITHUB_OUTPUT
+
   create-conda-package:
     name: Create conda package
     runs-on: ubuntu-latest
+    needs: inputs-sanity-check
     env:
-      REVISION: ${{ inputs.revision }} # Needed as an env variable for the conda recipe
-      VERSION: ${{ inputs.version }} # Needed as an env variable for the conda recipe
+      REVISION: ${{ needs.inputs-sanity-check.outputs.revision }} # Needed as an env variable for the conda recipe
+      VERSION: ${{ needs.inputs-sanity-check.outputs.version }} # Needed as an env variable for the conda recipe
     outputs:
-        paths: ${{ steps.conda-build.outputs.paths }}
+      paths: ${{ steps.conda-build.outputs.paths }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -46,9 +111,9 @@ jobs:
 
       - name: Build and upload conda package
         id: conda-build
-        uses: ACCESS-NRI/action-build-and-upload-conda-packages@davide/7-enable-multi-outputs
+        uses: ACCESS-NRI/action-build-and-upload-conda-packages@v3
         with:
-          meta_yaml_dir: packages/${{ inputs.package_name }}/recipe
+          meta_yaml_dir: packages/${{ needs.inputs-sanity-check.outputs.package_name }}/recipe
           user: ${{ secrets.ANACONDA_USERNAME }}
           token: ${{ secrets.ANACONDA_TOKEN }}
           conda_build_args: -c atteggiani -c accessnri -c conda-forge -c nodefaults
@@ -56,7 +121,7 @@ jobs:
   create-release:
     name: Create release
     runs-on: ubuntu-latest
-    needs: create-conda-package
+    needs: [set-tag-name, create-conda-package]
     permissions:
       contents: write
     steps:
@@ -64,23 +129,36 @@ jobs:
         id: create-tag
         run: |
           # Create tag
-          git tag '${{ env.TAG_NAME }}'
-          git push origin tag '${{ env.TAG_NAME }}'
+          git tag '${{ needs.set-tag-name.outputs.tag_name }}'
+          git push origin tag '${{ needs.set-tag-name.outputs.tag_name }}'
 
       - name: Create Release
         uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 #v2.3.2
         with:
-          tag_name: '${{ env.TAG_NAME }}'
-          name: '${{ env.RELEASE_NAME }}'
+          tag_name: '${{ needs.set-tag-name.outputs.tag_name }}'
+          name: '${{ needs.set-tag-name.outputs.release_name }}'
           generate_release_notes: false
           fail_on_unmatched_files: true
           files: |-
             ${{ needs.create-conda-package.outputs.paths }}
+  
+  trigger-next-release:
+    name: Trigger next package release
+    runs-on: ubuntu-latest
+    needs: [inputs-sanity-check, create-release]
+    if: ${{ needs.inputs-sanity-check.outputs.release_json != '[]' }}
+    steps:
+      - name: Release packages
+        run: |
+          echo "Releasing packages ..."
+          gh workflow run ${{ env.RELEASE_WORKFLOW }} --field release_json='${{ needs.inputs-sanity-check.outputs.release_json }}'
+          run_url=$(gh run list --workflow ${{ env.RELEASE_WORKFLOW }} --limit 1 --json url | jq '.[0].url')
+          echo "Release workflow run: $run_url"
 
   cleanup-tag-on-failure:
     name: Cleanup tag
     runs-on: ubuntu-latest
-    needs: [create-conda-package, create-release]
+    needs: [set-tag-name, create-release]
     # Run this job if any of the previous jobs failed (and don't skip if any of the needed jobs is skipped)
     if: ${{ ( always() && failure() ) || cancelled() }}
     permissions:
@@ -93,7 +171,7 @@ jobs:
   
       - name: Delete tag
         run: |
-          if git rev-parse '${{ env.TAG_NAME }}' &>/dev/null; then
-              git push origin :${{ env.TAG_NAME }}
-              echo "A job in the current workflow failed. Tag '${{ env.TAG_NAME }}' was deleted."
+          if git rev-parse '${{ needs.set-tag-name.outputs.tag_name }}' &>/dev/null; then
+              git push origin ':${{ needs.set-tag-name.outputs.tag_name }}'
+              echo "A job in the current workflow failed. Tag '${{ needs.set-tag-name.outputs.tag_name }}' was deleted."
           fi
